---
- name: Install dependacies
  hosts: '{{ target }}'
  become: '{{ use_sudo }}'
  become_user: root
  become_method: sudo
  tasks:
    - name: Install Prerequisites
      command: 'bench install prerequisites'

    - name: Setup logwatch
      command: 'bench setup role logwatch --admin_emails "{{ admin_emails }}"'
      when: '{{ is_production }}'

    - name: Install mariadb
      command: 'bench install mariadb --mysql_root_password {{ mysql_root_password }}'

    - name: Setup Locale
      command: 'bench setup role locale'
      when: '{{ is_production }}'
      
    - name: Setup swap
      command: 'bench setup role swap'

    - name: Install wkhtmltopdf
      command: 'bench install wkhtmltopdf'

    - name: Install nodejs
      command: 'bench install nodejs'

    - name: Setup psutil
      command: 'bench install psutil'

    - name: Setup nginx
      command: 'bench install nginx'
      when: '{{ is_production }}'

    - name: Setup fail2ban
      command: 'bench install fail2ban'
      when: '{{ is_production }}'

    - name: update Sudoers permissions
      command: 'bench setup sudoers frappe'
