---
- name: "Setup Esentials"
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Install the 'Development tools' package group (Redhat)
      yum: name="@Development tools" state=present
      when: ansible_os_family == 'RedHat'

    - name: Install EPEL
      yum: name='epel-release' state=present
      when: ansible_os_family == 'RedHat'

    - name: Install libselinux-python
      yum: name={{ item }} state=present
      with_items:
        - python-devel
        - python-setuptools
        - python-pip
        - libselinux-python
      when: ansible_os_family == 'RedHat'

    - name: Install libselinux-python
      apt: pkg={{ item }} state=present force=yes
      with_items:
        - build-essential
        - python-setuptools
        - python-dev
        - python-pip
        - libselinux-python
        - libffi-dev
        -libssl-dev
      when: ansible_os_family == 'Debian'
